spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/group_meet_planner
    username: postgres
    password: 1221
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
